### ISSUE TITLE
Where does the JSON assets come from?

### ISSUE THREAD

**Issue by clemsos** [KStasi/fa2-deployer#8]
Genuine question, just to know how they have been compiled. Many thanks for the nice tool !

**Comment by KStasi** [comment]
The contracts codebase came from https://github.com/tqtezos/smart-contracts with some modifications to have pausable/unpausable and mintable/non-mintable. They were compiled with ligo compiler

**Comment by KStasi** [comment]
Ligo contracts have been added to the repo
